#!/usr/bin/env bash
# Transfers a file from our client to a server:
# Accepts 4 parameters (The path to the file to be transferred,
# The IP of the server we want to transfer the file to,
# The username scp connects with, The path to the SSH private key that scp uses)
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file="$1"
	ip="$2"
	user="$3"
	private_key="$4"
	scp -o StrictHostKeyChecking=no -i "$private_key" "$file" "$user@$ip":~/; 
fi
