#!/usr/bin/env bash
# Installs nginx on server web-01
# server listens on port 80
# returns a page with string hello world
apt-get -y update
apt-get -y install nginx
#sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
mkdir -p /var/www/html
chmod -R 755 /var/www
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
