#!/usr/bin/env bash
# Write a manage_my_process Bash script that:
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

path=/var/run/my_process.pid

if [ "$1" = "start" ];then
    ./manage_my_process &
    echo "$$" > $path
    echo "manage_my_process started"
elif [ "$1" = "stop" ];then
    pkill -f ./manage_my_process
    rm $path
    echo 'manage_my_process stopped'
elif [ "$1" = "restart" ];then
     pkill -f ./manage_my_process
     rm $path
     ./manage_my_process &
     echo "$$" > $path
     echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
