#!/usr/bin/env bash
# ifs.sh
while IFS=":" read -r un pw uid gid uidI hd csh
do
    echo "The user $un is part of the $gid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pw, more info about the user here: $uidI"
done < "/etc/passwd"
