#!/usr/bin/env bash
#Displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.

index=0

while ((index < 10));
do
    if ((index==9));
    then
	echo "Hi"
    fi
    echo "Holberton School"
    ((index++))
done
