#!/usr/bin/env bash
# Write a script that prints bad luck on 4th loop, good luck on 8th and Holberton School else
x=0
while [ $x -lt 10 ]
do
    if [ $x = 3 ]; then
	echo "bad luck"
    elif [ $x = 7 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((x++))
done
