#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	j=1
	while [ $j -le 59 ]
	do
		echo $j
		j=$(( j + 1 )) # increase minutes by 1
	done
	h=$(( h + 1 )) # increase hours by 1
done
