#!/usr/bin/env bash
# loopey loop through the times
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
	echo $min
	    ((min++))
      done
      ((hour++))
done

