#!/usr/bin/env bash

#  install the ufw firewall and setup a few rules on web-01
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports
# 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
